server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: toy-guard

springdoc:
  swagger-ui:
    path: /swagger-ui.html

toyguard:
  token-secret: toy-guard-demo-secret
